version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes: 
  data: {}